apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example
            image: busybox:latest
            command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 10"]
          restartPolicy: Never
      backoffLimit: 4

