apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
data:
  my-secret-key: c2VjcmV0LXZhbHVl # base64 encoded value

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap-with-secret
data:
  my-config-key: "This is another config value"
  my-secret-key: c2VjcmV0LXZhbHVl # The secret value can be included as a string
